baseUrl : "https://domain/path_to_flarum/"
databaseConfiguration :
    host : "localhost"
    database : "flarum_database_name"
    prefix: "flarum_table_name_prefix_"
    username : "username"
    password : "password"
adminUser : 
    username : "adminuser"
    password : "adminpassword"
    password_confirmation : "adminpassword"
    email : "admin@email.com"
settings : 
    forum_title           : "Dataporten Test Forum"
    welcome_title         : "Velkommen til Dataporten Test Forum"
    welcome_message       : "Bare for testing :)"
    uninett-auth-dataporten.client_id     : "___ENTER____"
    uninett-auth-dataporten.client_secret : "___ENTER____"
    mail_from             : "noreply@dataporten.dev"
    default_locale        : "no"
    extensions_enabled    : "uninett-auth-dataporten"
    extensions_enabled    : "pladask-norwegian-bokmal"
    theme_colored_header  : 1
    theme_primary_color   : "#ed1b34"
    theme_secondary_color : "#010777"